In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [3]:
type(np.array(my_list))

numpy.ndarray

In [4]:
# convert a list to numpy array

arr = np.array(my_list)


In [5]:
arr

array([1, 2, 3])

In [6]:
#(start, end, difference between steps)

np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [7]:
#((row, column))

np.zeros((3, 5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
#((row, column))

np.ones((3, 5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# (start, end, number of elements)

np.linspace(0, 5, 10)


array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [10]:
#random number 

# (lowerlimit, uperlimit)
np.random.randint(0, 10)


3

In [11]:
# (lowerlimit, uperlimit, number of element)

np.random.randint(0, 10, 5)


array([6, 6, 2, 6, 7])

In [12]:
# (lowerlimit, uperlimit, (row, column))

np.random.randint(0, 10, (3, 4))


array([[6, 3, 3, 3],
       [1, 2, 7, 2],
       [2, 1, 2, 9]])

In [14]:
# seed is used to get the same random number everytime the code runs*****
#  *** in every cell seed need to be initialize. Otherwise it doesn't give same result ****

np.random.seed(101)
np.random.randint(0, 10, 5)


array([1, 6, 7, 9, 8])